# Generated by Django 4.0.1 on 2022-02-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_birthday_data_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday_data',
            name='user_id',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
